server:
  port: 8009

spring:
  redis:
      host: 192.168.1.10
      port: 6379
      database: 0
      password: leilei

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: false