server:
  port: 8002


mybatis:
  type-aliases-package: com.leilei.entity
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: MenuServer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/reservation
    username: root
    password: 111

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: MenuServer8002
    prefer-ip-address: true


