server:
  port: 8001


mybatis:
  type-aliases-package: com.leilei.entity
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: UserServer
  redis:
    host: 192.168.1.10
    port: 6379
    database: 0
    password: leilei
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/reservation
    username: root
    password: 111

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: UserServer8001
    prefer-ip-address: true


